apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: affiliate-api-hpa
  namespace: prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: affiliate-api
  minReplicas: 1
  maxReplicas: 44
  targetCPUUtilizationPercentage: 80