apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: beta
  name: pubsub-caller
spec:
  selector:
    matchLabels:
      POD_LABEL: pubsub-caller-pod-label
  replicas: 1
  template:
    metadata:
      labels:
        POD_LABEL: pubsub-caller-pod-label
      namespace: beta
    spec:
      serviceAccountName: beta-pubsub-publisher
      containers:
      - name: pubsub-caller-container
        image: asia-south1-docker.pkg.dev/weje-2023/gke-weje-images-india/cloud-resources:PubSubCaller-Beta1
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "10m"
            memory: "30Mi"