apiVersion: v1
kind: Service
metadata:
  namespace: beta
  name: pubsub-caller-svc
spec:
  ports:
  - port: 83
    targetPort: 8080
  selector:
    POD_LABEL: pubsub-caller-pod-label
  type: ClusterIP