apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pubsub-caller-hpa
  namespace: prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pubsub-caller
  minReplicas: 1
  maxReplicas: 13
  targetCPUUtilizationPercentage: 80