apiVersion: v1
kind: Service
metadata:
  namespace: prod
  name: blackjack-web3caller-svc
spec:
  ports:
  - port: 9023
    targetPort: 8080
  selector:
    POD_LABEL: web3caller-blackjack-pod-label
  type: ClusterIP