apiVersion: v1
kind: Service
metadata:
  namespace: beta
  name: affiliate-api-svc
spec:
  ports:
  - port: 101
    targetPort: 8080
  selector:
    SVC_LABEL: affiliate-api-svc-label
  type: ClusterIP