apiVersion: v1
kind: Service
metadata:
  namespace: beta
  name: get-doc-svc
  annotations:
    networking.gke.io/max-rate-per-endpoint: "10"
spec:
  ports:
  - port: 9006
    targetPort: 8080
  selector:
    POD_LABEL: get-doc-pod-label
  type: ClusterIP