apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: store-autoscale
  namespace: beta
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: get-doc
  minReplicas: 1
  maxReplicas: 8
  metrics:
  - type: Object
    object:
      describedObject:
        kind: Service
        name: get-doc-svc
      metric:
        name: "autoscaling.googleapis.com|gclb-capacity-utilization"
      target:
        averageValue: "80"
        type: AverageValue