apiVersion: v1
kind: Service
metadata:
  namespace: beta
  name: ludo-server-svc
  annotations:
    networking.gke.io/max-rate-per-endpoint: "100"
spec:
  ports:
  - port: 9016
    targetPort: 3001
  selector:
    POD_LABEL: ludo-pod-label
  type: ClusterIP