apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: ludo-hcheck
  namespace: beta
spec:
  default:
    checkIntervalSec: 300
    timeoutSec: 18
    healthyThreshold: 1
    unhealthyThreshold: 1
    logConfig:
      enabled: false
    config:
      type: HTTP
      httpHealthCheck:
        portSpecification: USE_FIXED_PORT
        port: 3001
        requestPath: /LudoServer/hCheck
        proxyHeader: NONE
  targetRef:
    group: ""
    kind: Service
    name: ludo-server-svc