apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: beta
  name: ludo-server
spec:
  selector:
    matchLabels:
      POD_LABEL: ludo-pod-label
  replicas: 1
  template:
    metadata:
      labels:
        POD_LABEL: ludo-pod-label
      namespace: beta
    spec:
      serviceAccountName: beta-fire-w
      containers:
      - name: ludo-container
        image: asia-south1-docker.pkg.dev/weje-2023/gke-weje-images-india/ludo-server:ludo-homw-won
        ports:
        - containerPort: 3001
        resources:
          requests:
            cpu: "1m"
            memory: "140Mi"
        envFrom:
          - secretRef:
              name: beta-poker-secrets