apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ludo-server-hpa
  namespace: prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prod-ludo-server
  minReplicas: 1
  maxReplicas: 44
  metrics:
  - type: Object
    object:
      describedObject:
        kind: Service
        name: ludo-server-svc
      metric:
        name: "autoscaling.googleapis.com|gclb-capacity-utilization"
      target:
        averageValue: "80"
        type: AverageValue
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 100