apiVersion: v1
kind: Service
metadata:
  namespace: beta
  name: settings-nickname-svc
spec:
  ports:
  - port: 9011
    targetPort: 8080
  selector:
    POD_LABEL: settings-nickanme-pod-label
  type: ClusterIP