apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: beta-settings-nickname-hcheck
  namespace: beta
spec:
  default:
    checkIntervalSec: 300
    timeoutSec: 9
    healthyThreshold: 1
    unhealthyThreshold: 1
    logConfig:
      enabled: false
    config:
      type: HTTP
      httpHealthCheck:
        portSpecification: USE_FIXED_PORT
        port: 8080
        requestPath: /ChangeNick/HealthCheck
        proxyHeader: NONE
  targetRef:
    group: ""
    kind: Service
    name: settings-nickname-svc