apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: prod
  name: settings-nickanme
spec:
  selector:
    matchLabels:
      POD_LABEL: settings-nickanme-pod-label
  replicas: 1
  template:
    metadata:
      labels:
        POD_LABEL: settings-nickanme-pod-label
      namespace: prod
    spec:
      serviceAccountName: fire-w-auth-w
      containers:
      - name: settings-nickanme-container
        image: asia-south1-docker.pkg.dev/weje-2023/gke-weje-images-india/settings:ChangeNick-PrivateRouteGmail
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "30m"
            memory: "75Mi"
        envFrom:
          - configMapRef:
              name: prod-config