apiVersion: v1
kind: Service
metadata:
  namespace: beta
  name: settings-transhistory-svc
spec:
  ports:
  - port: 9015
    targetPort: 8080
  selector:
    POD_LABEL: settings-transhistory-pod-label
  type: ClusterIP