apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: beta-settings-transhistory-hcheck
  namespace: beta
spec:
  default:
    checkIntervalSec: 300
    timeoutSec: 18
    healthyThreshold: 1
    unhealthyThreshold: 1
    logConfig:
      enabled: false
    config:
      type: HTTP
      httpHealthCheck:
        portSpecification: USE_FIXED_PORT
        port: 8080
        requestPath: /TransHist/HealthCheck
        proxyHeader: NONE
  targetRef:
    group: ""
    kind: Service
    name: settings-transhistory-svc