apiVersion: v1
kind: Service
metadata:
  namespace: prod
  name: settings-transhistory-svc
  annotations:
    networking.gke.io/max-rate-per-endpoint: "10"
spec:
  ports:
  - port: 9015
    targetPort: 8080
  selector:
    POD_LABEL: settings-transhistory-pod-label
  type: ClusterIP