FROM python:3.9-slim
ENV PYTHONUNBUFFERED True
WORKDIR /app
RUN adduser -u 5678 --disabled-password --gecos "" appuser \
&& chown -R appuser . \
&& pip install gunicorn flask \
&& pip install firebase-admin
USER appuser
COPY . ./
CMD exec gunicorn --bind :$PORT --workers 1 --threads 8 --timeout 0 wsgi:app
