apiVersion: v1
kind: Service
metadata:
  namespace: beta
  name: create-table-svc
spec:
  ports:
  - port: 9007
    targetPort: 8080
  selector:
    POD_LABEL: create-table-pod-label
  type: ClusterIP