apiVersion: v1
kind: Service
metadata:
  namespace: prod
  name: create-table-svc
  annotations:
    networking.gke.io/max-rate-per-endpoint: "20"
spec:
  ports:
  - port: 9007
    targetPort: 8080
  selector:
    POD_LABEL: create-table-pod-label
  type: ClusterIP