apiVersion: v1
kind: Service
metadata:
  namespace: beta
  name: sport-bets-svc
spec:
  ports:
  - port: 9018
    targetPort: 8080
  selector:
    POD_LABEL: sport-bets-api-pod-label
  type: ClusterIP