apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: beta
  name: sport-bets-api
spec:
  selector:
    matchLabels:
      POD_LABEL: sport-bets-api-pod-label
  replicas: 1
  template:
    metadata:
      labels:
        POD_LABEL: sport-bets-api-pod-label
      namespace: beta
    spec:
      serviceAccountName: beta-fire-w
      containers:
      - name: sport-bets-api-container
        image: asia-south1-docker.pkg.dev/weje-2023/gke-weje-images-india/sportsbetapi:SportsBetApi-call-util-update
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "1m"
            memory: "120Mi"
        env:
        - name: AFFILIATE_BATCH_TRESHOLD
          valueFrom:
            configMapKeyRef:
              name: beta-config
              key: AFFILIATE_BATCH_TRESHOLD
        - name: AFFILIATE_BATCH_SIZE
          valueFrom:
            configMapKeyRef:
              name: beta-config
              key: AFFILIATE_BATCH_SIZE
        - name: UPDATE_AFFILIATE_EARN_SPORT_BET_TOPIC_PATH
          valueFrom:
            configMapKeyRef:
              name: beta-config
              key: UPDATE_AFFILIATE_EARN_SPORT_BET_TOPIC_PATH
        - name: PUBSUB_CALLER_SVC_NAME
          valueFrom:
            configMapKeyRef:
              name: beta-config
              key: PUBSUB_CALLER_SVC_NAME
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: beta-poker-secrets
              key: REDIS_PORT
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: beta-poker-secrets
              key: REDIS_HOST
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: beta-poker-secrets
              key: REDIS_PASSWORD
        - name: TASK_CALLER_API
          valueFrom:
            configMapKeyRef:
              name: beta-config
              key: TASK_CALLER_API
        - name: DB_PREFIX
          valueFrom:
            configMapKeyRef:
              name: beta-config
              key: DB_COLL_PREFIX
        - name: SPORTS_BET_EVENT_API
          valueFrom:
            configMapKeyRef:
              name: beta-config
              key: SPORTS_BET_EVENT_API
        envFrom:
          - configMapRef:
              name: beta-web3-config
          - secretRef:
              name: beta-secrets
