apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: sport-bets-api-hcheck
  namespace: prod
spec:
  default:
    checkIntervalSec: 300
    timeoutSec: 9
    healthyThreshold: 1
    unhealthyThreshold: 1
    logConfig:
      enabled: false
    config:
      type: HTTP
      httpHealthCheck:
        portSpecification: USE_FIXED_PORT
        port: 8080
        requestPath: /SportsBet/hCheck
        proxyHeader: NONE
  targetRef:
    group: ""
    kind: Service
    name: sport-bets-svc