apiVersion: v1
kind: Service
metadata:
  namespace: prod
  name: sport-bets-svc
  annotations:
    networking.gke.io/max-rate-per-endpoint: '20'
spec:
  ports:
  - port: 9018
    targetPort: 8080
  selector:
    POD_LABEL: sport-bets-api-pod-label
  type: ClusterIP