apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: leave-child-gmail-hpa
  namespace: prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: leave-child-gmail-bonus
  minReplicas: 1
  maxReplicas: 13
  targetCPUUtilizationPercentage: 80