apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: leave-child-affi-hpa
  namespace: prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: leave-child-affiliate
  minReplicas: 1
  maxReplicas: 144
  targetCPUUtilizationPercentage: 80