apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: prod
  name: blackjack-in-listener
spec:
  selector:
    matchLabels:
      POD_LABEL: blackjack-in-pod-label
  replicas: 1
  template:
    metadata:
      labels:
        POD_LABEL: blackjack-in-pod-label
      namespace: prod
    spec:
      containers:
      - name: blackjack-in-listener-container
        image: asia-south1-docker.pkg.dev/weje-2023/gke-weje-images-india/web3:BuyInListenSetProviderExitAfter3reconnects
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "21m"
            memory: "63Mi"
        env:
        - name: GAME_SERVER_INDEX
          value: '1'
        envFrom:
          - configMapRef:
              name: prod-web3-config
          - configMapRef:
              name: prod-config