apiVersion: v1
kind: Service
metadata:
  namespace: beta
  name: beta-blackjack-server-svc
  annotations:
    networking.gke.io/max-rate-per-endpoint: "13"
spec:
  ports:
  - port: 9008
    targetPort: 3001
  selector:
    POD_LABEL: bj-server-pod-label
  type: ClusterIP