apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: bj-server-hcheck
  namespace: prod
spec:
  default:
    checkIntervalSec: 300
    timeoutSec: 18
    healthyThreshold: 1
    unhealthyThreshold: 1
    logConfig:
      enabled: false
    config:
      type: HTTP
      httpHealthCheck:
        portSpecification: USE_FIXED_PORT
        port: 3001
        requestPath: /BlackjackServer/hCheck
        proxyHeader: NONE
  targetRef:
    group: ""
    kind: Service
    name: blackjack-server-svc