apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: bj-server-backendpolicy
  namespace: prod
spec:
  default:
    logging:
      enabled: false
      #sampleRate: 0
    connectionDraining:
      drainingTimeoutSec: 88
    sessionAffinity:
      type: CLIENT_IP
    timeoutSec: 93
    #maxRatePerEndpoint: 15
    #securityPolicy: example-security-policy
  targetRef:
    group: ""
    kind: Service
    name: blackjack-server-svc
