# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transData.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftransData.proto\"\xb2\x01\n\x0e\x43ustomerRecord\x12\x0b\n\x03uid\x18\x01 \x02(\t\x12\x0c\n\x04name\x18\x02 \x02(\t\x12\x1e\n\x04\x46rom\x18\x03 \x01(\t:\x10universal_Tables\x12\x13\n\x0b\x63oinsAmount\x18\x04 \x02(\x02\x12\x0b\n\x03\x66\x65\x65\x18\x05 \x02(\x02\x12\x0c\n\x04\x64\x61te\x18\x06 \x02(\t\x12\x12\n\nfirebaseID\x18\x07 \x02(\t\x12\x0f\n\x07\x66rom_id\x18\x08 \x02(\t\x12\x10\n\x08\x63urrency\x18\t \x02(\t')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CUSTOMERRECORD']._serialized_start=20
  _globals['_CUSTOMERRECORD']._serialized_end=198
# @@protoc_insertion_point(module_scope)
