apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ludo-web3-hpa
  namespace: prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prod-web3caller-ludo
  minReplicas: 1
  maxReplicas: 44
  targetCPUUtilizationPercentage: 80