apiVersion: v1
kind: Service
metadata:
  namespace: prod
  name: ludo-web3caller-svc
spec:
  ports:
  - port: 9033
    targetPort: 8080
  selector:
    POD_LABEL: web3caller-ludo-pod-label
  type: ClusterIP