apiVersion: v1
kind: Service
metadata:
  namespace: beta
  name: rapid-api-caller-svc
spec:
  ports:
  - port: 89
    targetPort: 8080
  selector:
    SVC_LABEL: sport-rapid-api-pod-label
  type: ClusterIP