apiVersion: v1
kind: Service
metadata:
  namespace: beta
  name: beta-poker-server-svc
  annotations:
    networking.gke.io/max-rate-per-endpoint: "8"
spec:
  ports:
  - port: 9002
    targetPort: 3001
    name: http
  selector:
    POD_LABEL: beta-poker-server-pod-label
  type: ClusterIP