apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: beta
  name: beta-poker-server
spec:
  selector:
    matchLabels:
      POD_LABEL: beta-poker-server-pod-label
  replicas: 1
  template:
    metadata:
      labels:
        POD_LABEL: beta-poker-server-pod-label
      namespace: beta
    spec:
      serviceAccountName: beta-fire-w
      containers:
      - name: beta-poker-server-container
        image: asia-south1-docker.pkg.dev/weje-2023/gke-weje-images-india/poker-server:poker-hand-nan-poolsize
        ports:
        - containerPort: 3001
        resources:
          requests:
            cpu: "1m"
            memory: "155Mi"
        envFrom:
          - secretRef:
              name: beta-poker-secrets
