apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: beta-poker-server-hcheck
  namespace: beta
spec:
  default:
    checkIntervalSec: 130
    timeoutSec: 18
    healthyThreshold: 1
    unhealthyThreshold: 2
    logConfig:
      enabled: false
    config:
      type: HTTP
      httpHealthCheck:
        portSpecification: USE_FIXED_PORT
        port: 3001
        requestPath: /PokerServer/hCheck
        proxyHeader: NONE
  targetRef:
    group: ""
    kind: Service
    name: beta-poker-server-svc