apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: poker-server-hcheck
  namespace: prod
spec:
  default:
    checkIntervalSec: 120
    timeoutSec: 10
    healthyThreshold: 1
    unhealthyThreshold: 1
    logConfig:
      enabled: false
    config:
      type: HTTP
      httpHealthCheck:
        portSpecification: USE_FIXED_PORT
        port: 3001
        requestPath: /PokerServer/hCheck
        proxyHeader: NONE
  targetRef:
    group: ""
    kind: Service
    name: poker-server-svc