apiVersion: v1
kind: Service
metadata:
  namespace: prod
  name: poker-server-svc
  annotations:
    networking.gke.io/max-rate-per-endpoint: "15"
spec:
  ports:
  - port: 9002
    targetPort: 3001
    name: http
  selector:
    POD_LABEL: poker-server-pod-label
  type: ClusterIP