apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: beta
  name: beta-leave-table
spec:
  selector:
    matchLabels:
      POD_LABEL: beta-leave-table-pod-label
  replicas: 1
  template:
    metadata:
      labels:
        POD_LABEL: beta-leave-table-pod-label
      namespace: beta
    spec:
      serviceAccountName: beta-pubsub-publisher
      containers:
      - name: beta-leave-table-container
        image: asia-south1-docker.pkg.dev/weje-2023/gke-weje-images-india/tables:LeaveTable-LudoWeb3onEachHand-Affiliate
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "1m"
            memory: "60Mi"
        envFrom:
          - configMapRef:
              name: beta-config