apiVersion: v1
kind: Service
metadata:
  namespace: beta
  name: beta-leave-table-svc
spec:
  ports:
  - port: 82
    targetPort: 8080
  selector:
    POD_LABEL: beta-leave-table-pod-label
  type: ClusterIP