apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: leave-table-hpa
  namespace: prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prod-leave-table
  minReplicas: 1
  maxReplicas: 65
  targetCPUUtilizationPercentage: 80