apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: prod
  name: prod-leave-table
spec:
  selector:
    matchLabels:
      POD_LABEL: leave-table-pod-label
  replicas: 1
  template:
    metadata:
      labels:
        POD_LABEL: leave-table-pod-label
      namespace: prod
    spec:
      terminationGracePeriodSeconds: 88
      serviceAccountName: pubsub-publisher
      containers:
      - name: leave-table-container
        image: asia-south1-docker.pkg.dev/weje-2023/gke-weje-images-india/tables:LeaveTable-LudoWeb3onEachHand-AffiBetAmount
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "29m"
            memory: "72Mi"
        envFrom:
          - configMapRef:
              name: prod-config