apiVersion: v1
kind: Service
metadata:
  namespace: beta
  name: sport-sql-caller-svc
spec:
  ports:
  - port: 9019
    targetPort: 3000
  selector:
    POD_LABEL: sport-sql-caller-pod-label
  type: ClusterIP