apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: beta
  name: sport-sql-caller
spec:
  selector:
    matchLabels:
      POD_LABEL: sport-sql-caller-pod-label
  replicas: 1
  template:
    metadata:
      labels:
        POD_LABEL: sport-sql-caller-pod-label
      namespace: beta
    spec:
      serviceAccountName: zero-perm
      containers:
      - name: sport-sql-caller-container
        image: asia-south1-docker.pkg.dev/weje-2023/gke-weje-images-india/sportsapi:SportsApi-status-update
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "9m"
            memory: "75Mi"
        env:
        - name: ENV_MODE
          valueFrom:
            secretKeyRef:
              name: beta-poker-secrets
              key: ENV_MODE
        envFrom:
          - secretRef:
              name: beta-secrets
