apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: sport-sql-caller-hcheck
  namespace: prod
spec:
  default:
    checkIntervalSec: 300
    timeoutSec: 4
    healthyThreshold: 1
    unhealthyThreshold: 1
    logConfig:
      enabled: false
    config:
      type: HTTP
      httpHealthCheck:
        portSpecification: USE_FIXED_PORT
        port: 3000
        requestPath: /prod/SportsApi/hCheck
        proxyHeader: NONE
  targetRef:
    group: ""
    kind: Service
    name: sport-sql-caller-svc