apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: beta
  name: beta-web3caller
spec:
  selector:
    matchLabels:
      POD_LABEL: beta-web3caller-pod-label
  replicas: 1
  template:
    metadata:
      labels:
        POD_LABEL: beta-web3caller-pod-label
      namespace: beta
    spec:
      serviceAccountName: zero-perm
      containers:
      - name: beta-web3caller-container
        image: asia-south1-docker.pkg.dev/weje-2023/gke-weje-images-india/web3:FuncCaller-GasLimit150-gasEstimateErr
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "1m"
            memory: "60Mi"
        env:
        - name: GAME_SERVER_INDEX
          value: '0'
        envFrom:
          - configMapRef:
              name: beta-web3-config
          - configMapRef:
              name: beta-config
          - secretRef:
              name: beta-secrets