apiVersion: v1
kind: Service
metadata:
  namespace: prod
  name: prod-web3caller-svc
spec:
  ports:
  - port: 9003
    targetPort: 8080
  selector:
    POD_LABEL: web3caller-pod-label
  type: ClusterIP