apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: prod
  name: sport-bet-child-affiliate
spec:
  selector:
    matchLabels:
      POD_LABEL: sport-bet-child-affiliate-pod-label
  replicas: 1
  template:
    metadata:
      labels:
        POD_LABEL: sport-bet-child-affiliate-pod-label
      namespace: prod
    spec:
      terminationGracePeriodSeconds: 68
      serviceAccountName: fire-w-auth-r-pubsub-pullsub
      containers:
      - name: sport-bet-child-affiliate-container
        image: asia-south1-docker.pkg.dev/weje-2023/gke-weje-images-india/affiliate:SportBetChild-UpdateAffiEarn3
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "18m"
            memory: "60Mi"
        envFrom:
          - configMapRef:
              name: prod-config